development:
  adapter: postgresql
  encoding: unicode
  database: sashafklein_development
  pool: 5
  username: sashafklein
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sashafklein_test
  pool: 5
  username: sashafklein
  password: